# Generated by Django 4.0.4 on 2022-04-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='time',
            new_name='timeprocess',
        ),
    ]
