# Generated by Django 4.0.4 on 2022-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0002_rename_time_dishes_timeprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
