# Generated by Django 4.0.4 on 2022-04-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0003_alter_dishes_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='tag',
            new_name='tags',
        ),
    ]
