# Generated by Django 4.0.4 on 2022-04-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0004_rename_tag_dishes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.TextField(),
        ),
    ]
