# Generated by Django 4.0.4 on 2022-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0005_alter_dishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='calories',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
