# Generated by Django 4.0.4 on 2022-04-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0006_alter_dishes_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='rating',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='timeprocess',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
