# Generated by Django 4.0.4 on 2022-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0007_alter_dishes_rating_alter_dishes_timeprocess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kartinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='complexity',
            options={'verbose_name': 'Уровень сложности приготовления', 'verbose_name_plural': 'Уровни сложности приготовления'},
        ),
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
