# Generated by Django 4.0.4 on 2022-04-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0008_kartinka_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kartinka',
        ),
        migrations.AddField(
            model_name='dishes',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='images_full'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecipeapp.category'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecipeapp.complexity'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_small'),
        ),
    ]
