# Generated by Django 4.0.4 on 2022-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0009_delete_kartinka_dishes_image_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description_full',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='ingredients_clr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
    ]
