# Generated by Django 4.0.4 on 2022-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0010_dishes_description_full_dishes_ingredients_clr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexity',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
