# Generated by Django 4.0.4 on 2022-05-12 16:44

from django.db import migrations, models
import getrecipeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipeapp', '0012_alter_dishes_image_alter_dishes_image_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер картинки 1 мб, резрешение 150х150', null=True, upload_to='images_small', validators=[getrecipeapp.models.validate_image]),
        ),
    ]
